import styles from './index.module.scss'
import Head from 'next/head'
import { RiMovie2Line } from 'react-icons/ri';
import Link from 'next/Link'

const Layout = ({children}) => {
    return (
    <div className={styles.container}>
        <Head>
            <title>Movie Ranks</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <header className={styles.header}>
            <Link href='/'>
            <div>
            <RiMovie2Line />
            <h1>Movie</h1>
            <h2>Ranks</h2>
            </div>
            </Link>
        </header>
        <main className={styles.main}>
        {children}
        </main>

        <footer className={styles.footer}>
        COPYRIGHT&copy; 2022 by Kaniewski 
        </footer>
    </div>
    );
}

export default Layout;